### ISSUE TITLE
Is it possible to share the grafana dashboad

### ISSUE THREAD

**Issue by sunilsankar** [gnur/prometheus-p1-exporter#2]
Awesome exporter btw

**Comment by sunilsankar** [comment]
Nevermind built one

**Comment by EuleMitKeule** [comment]
I would also be interested in the grafana dashboard! I am currently struggeling how I can visualize my running total energy consumption in this form:
![grafik](https://user-images.githubusercontent.com/47421406/231012777-dc1b4b32-8dda-40a3-a603-701994e9e2d4.png)
